"""
report_builder.py — converts Bob's synthesized markdown report (plus the
raw per-module reports) into a single, styled, readable HTML document.
"""

import re
import markdown
from pathlib import Path
from datetime import datetime


PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — ArchForge Onboarding Guide</title>
<style>
  :root {{
    --bg: #ffffff; --fg: #1f2328; --muted: #57606a; --border: #d0d7de;
    --code-bg: #f6f8fa; --accent: #6e40c9; --table-stripe: #f6f8fa;
  }}
  body {{
    font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif;
    max-width: 900px; margin: 0 auto; padding: 40px 24px 80px;
    color: var(--fg); background: var(--bg); line-height: 1.6;
  }}
  h1 {{ font-size: 30px; border-bottom: 1px solid var(--border); padding-bottom: 12px; }}
  h2 {{ font-size: 22px; margin-top: 40px; border-bottom: 1px solid var(--border); padding-bottom: 8px; }}
  h3 {{ font-size: 17px; margin-top: 28px; color: var(--accent); }}
  h4 {{ font-size: 15px; margin-top: 20px; }}
  code {{ background: var(--code-bg); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }}
  pre {{ background: var(--code-bg); padding: 14px; border-radius: 8px; overflow-x: auto; }}
  pre code {{ background: none; padding: 0; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 14px; }}
  th, td {{ border: 1px solid var(--border); padding: 8px 12px; text-align: left; }}
  tr:nth-child(even) {{ background: var(--table-stripe); }}
  a {{ color: var(--accent); }}
  .header-banner {{
    background: linear-gradient(135deg, #1a1030, #2d1b4e);
    color: white; padding: 32px; border-radius: 12px; margin-bottom: 32px;
  }}
  .header-banner h1 {{ border: none; margin: 0 0 8px; color: white; }}
  .header-banner p {{ margin: 0; color: #c9b8f0; }}
  .badge {{
    display: inline-block; background: rgba(255,255,255,0.15); padding: 4px 10px;
    border-radius: 20px; font-size: 12px; margin-top: 12px;
  }}
  details {{ margin-top: 40px; border: 1px solid var(--border); border-radius: 8px; padding: 12px 16px; }}
  summary {{ cursor: pointer; font-weight: 600; color: var(--muted); }}
  .mermaid {{ background: var(--code-bg); padding: 20px; border-radius: 8px; }}
  hr {{ border: none; border-top: 1px solid var(--border); margin: 32px 0; }}
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.min.js"></script>
<script>mermaid.initialize({{ startOnLoad: true, theme: 'neutral' }});</script>
</head>
<body>

<div class="header-banner">
  <h1>{title}</h1>
  <p>Automated onboarding analysis generated by ArchForge, powered by IBM Bob 2.0</p>
  <span class="badge">Generated {timestamp}</span>
</div>

{main_content}

<details>
<summary>Raw per-module investigation reports (unedited)</summary>
{raw_reports}
</details>

</body>
</html>
"""


def _escape_prose_angle_brackets(md_text: str) -> str:
    """
    Bob's prose sometimes contains literal angle brackets that aren't real
    HTML/markdown (e.g. 'app_<locale>.arb', 'Map<String, bool>'). Left
    as-is, the browser treats them as broken tags and corrupts the page.
    This escapes '&', '<', '>' in prose sections only — fenced code blocks
    (```...```) are left untouched so python-markdown's own fenced_code
    extension can escape them correctly exactly once.
    """
    parts = re.split(r'(```.*?```)', md_text, flags=re.DOTALL)
    for i, part in enumerate(parts):
        if not part.startswith("```"):
            parts[i] = (
                part.replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;")
            )
    return "".join(parts)


def _markdown_to_html(md_text: str) -> str:
    md_text = _escape_prose_angle_brackets(md_text)
    html = markdown.markdown(
        md_text,
        extensions=["fenced_code", "tables", "toc"],
    )
    # python-markdown puts the language class on <code>, but mermaid.js
    # looks for class="mermaid" on the <pre> itself.
    html = re.sub(
        r'<pre><code class="language-mermaid">',
        '<pre class="mermaid"><code>',
        html,
    )
    return html


def build_report(repo_name: str, module_reports: dict, final_report_text: str) -> Path:
    output_dir = Path("output")
    output_dir.mkdir(exist_ok=True)

    timestamp_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = output_dir / f"{repo_name}_onboarding_{file_timestamp}.html"

    main_html = _markdown_to_html(final_report_text)

    raw_sections = []
    for module_name, report in module_reports.items():
        raw_sections.append(f"<h4>{module_name}</h4>")
        raw_sections.append(_markdown_to_html(report))
    raw_html = "\n".join(raw_sections)

    page = PAGE_TEMPLATE.format(
        title=f"{repo_name} — Onboarding Guide",
        timestamp=timestamp_str,
        main_content=main_html,
        raw_reports=raw_html,
    )

    output_path.write_text(page, encoding="utf-8")
    return output_path